apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-ingest-management
  labels:
    app: agent-ingest-management
spec:
  selector:
    matchLabels:
      app: agent-ingest-management
  template:
    metadata:
      labels:
        app: agent-ingest-management
    spec:
      containers:
        - name: agent-ingest-management
          image: docker.elastic.co/beats/elastic-agent:8.0.0-SNAPSHOT
          env:
            - name: FLEET_ENROLL
              value: "1"
            - name: FLEET_SETUP
              value: "1"
            - name: KIBANA_HOST
              value: "http://kibana:5601"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "changeme"

