apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ingest-management
  namespace: kube-system
  labels:
    app: registry-ingest-management
spec:
  selector:
    matchLabels:
      app: registry-ingest-management
  template:
    metadata:
      labels:
        app: registry-ingest-management
    spec:
      volumes:
        - name: registry-storage
          hostPath:
            path: /etc/build/public
      containers:
        - name: registry-ingest-management
          image: docker.elastic.co/package-registry/package-registry:master
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /registry/public
              name: registry-storage
          ports:
            - containerPort: 8080
              name: registry
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
  labels:
    app: registry-ingest-management
spec:
  type: NodePort
  selector:
    app: registry-ingest-management
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30568
