title: Prometheus remote_write metrics
release: beta
type: metrics
streams:
- input: prometheus/metrics
  vars:
  - name: host
    type: text
    title: Host
    multi: false
    required: true
    show_user: true
    default: localhost
  - name: port
    type: text
    title: Port
    multi: false
    required: true
    show_user: true
    default: "9201"
  - name: ssl.certificate
    type: text
    title: Ssl Certificate
    multi: false
    required: false
    show_user: true
    default: /etc/pki/server/cert.pem
  - name: ssl.key
    type: text
    title: Ssl Key
    multi: false
    required: false
    show_user: true
    default: /etc/pki/server/cert.key
  title: Prometheus remote_write metrics
  description: Collect Prometheus remote_write metrics
